name: PR CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate Branching Strategy
        run: |
          TARGET="${{ github.event.pull_request.base.ref }}"
          SOURCE="${{ github.event.pull_request.head.ref }}"
          echo "🔍 Validating: $SOURCE → $TARGET"
          [[ "$TARGET" == "devel" && ! "$SOURCE" =~ ^(feat|bugfix)/.* ]] && echo "❌ Only feat/* or bugfix/* → devel" && exit 1
          [[ "$TARGET" == "stage" && "$SOURCE" != "devel" ]] && echo "❌ Only devel → stage" && exit 1
          [[ "$TARGET" == "prod" && "$SOURCE" != "stage" ]] && echo "❌ Only stage → prod" && exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install

      - name: Lint (ESLint)
        run: npm run lint

      - name: Format (Prettier)
        run: npm run prettier -- --write

      - name: Test (Jest)
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build

  comment:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ok = '${{ needs.build.result }}' === 'success';
            await github.rest.issues.createComment({
              owner:       context.repo.owner,
              repo:        context.repo.repo,
              issue_number: context.issue.number,
              body: ok
                ? '✅ Build succeeded!! All checks passed.'
                : '❌ Build failed! Please check the logs.'
            });