name: CI Pipeline

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Run formatter
      run: npm run prettier --write

    - name: Run tests
      env: 
        CI: true
      run: npm run test

    - name: Build project
      run: npm run build

  comment:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ok = '${{ needs.build.result }}' === 'success';
            await github.rest.issues.createComment({
              owner:       context.repo.owner,
              repo:        context.repo.repo,
              issue_number: context.issue.number,
              body: ok
                ? '✅ Build succeeded! All checks passed.'
                : '❌ Build failed! Please check the logs.'
            });

  auto-approve:
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}