name: PR CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint (ESLint)
        run: npm run lint

      - name: Format (Prettier)
        run: npm run prettier -- --write

      - name: Test (Jest)
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build

  comment:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ok = '${{ needs.build.result }}' === 'success';
            await github.rest.issues.createComment({
              owner:       context.repo.owner,
              repo:        context.repo.repo,
              issue_number: context.issue.number,
              body: ok
                ? '✅ Build succeeded! All checks passed.'
                : '❌ Build failed! Please check the logs.'
            });